### ISSUE TITLE
Up

### ISSUE THREAD

**Issue by Weefle** [olsdavis/GameStack#3]
Bonjour, quand le projet va-t-il reprendre ou est-il abandonné?

**Comment by olsdavis** [comment]
Il est au moins mis de côté et voire même peut-être abandonné.

**Comment by Weefle** [comment]
J'aimerais au moins savoir si il y a une alternative?
Si tu connais un autre projet du même type j'en ai vraiment besoin et je ne sais pas encore coder ce type de système.
Merci.

**Comment by olsdavis** [comment]
Je n'en connais pas, désolé
